---
- name: DBserver setup
  hosts: dbservers
  become: yes

  vars: # Playbook variables
    dbname: electric
    dbuser: current
    dbpass: tesla

  tasks:
  - debug:
      msg: "The dbname is{{dbname}}"

  - debug:
      var: dbuser

  - name: Install maria-DB server
    ansible.builtin.yum:
      name: mariadb-server
      state: present

  - name: Install PyMYsql
    ansible.builtin.yum:
      name: python3-PyMySQL
      state: present

  - name: Start mariadb service
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes

  - name: Create a new databas
    community.mysql.mysql_db:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: "{{dbname}}"
      state: present

  - name: Create database user
    community.mysql.mysql_user:
      name: "{{dbuser}}"
      password: "{{dbpass}}"
      priv: '*.*:ALL'
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock
    register: dbout   # Will store all the json output into dbout variable
    # use debug to print it

  - name: print dbout variable
    debug:
      var: dbout