---
- name: Print Facts
  hosts: all
  tasks:
  - name: Print OS Name
    debug:
      var: ansible_distribution

  - name: Print RAM
    debug:
      var: ansible_memory_mb.real.free

  - name: Print SElinux mode
    debug:
      var: ansible_selinux.mode

  - name: Print Processors name
    debug:
      var: ansible_processor[2]
